naoyuki2/r6-devteam-firsthalf

- src/index.ts
- src/lib/hash.ts
- src/module/auth/auth.controller.ts
- src/module/auth/auth.service.ts
- src/module/auth/auth.type.ts
- src/module/user/user.controller.ts
- src/module/user/user.serializer.ts
- src/module/user/user.service.ts
サインイン機能を作成しました
APIdogで動作するのを確認済みです
> Feature sign in backend

- src/module/auth/auth.controller.ts
User用のSerializerを作成しました。
APIdog確認済みです。
> userSerializerの作成

- src/module/auth/auth.controller.ts
- src/module/auth/auth.service.ts
- src/module/auth/auth.type.ts
- src/module/request/request.controller.ts
- src/module/request/request.type.ts
- src/module/user/user.controller.ts
- src/module/user/user.service.ts
- src/module/user/user.type.ts
各controllerで呼び出すエンドポイントを定数で呼び出せるようにしました。
定数名は各module事のtypeファイルの通りです。
ついでにUser情報をidごとに取得するgetメソッドを作成しました、まとめてレビューお願いします。
> エンドポイントを定数で呼び出せるように修正

- package-lock.json
- package.json
- src/lib/axios.instance.ts
- src/module/page/page.controller.ts
- src/module/request/request.client.ts
- src/module/request/request.controller.ts
- src/module/request/request.serializer.ts
- src/module/request/request.service.ts
- src/module/request/request.type.ts
- src/view/card.ejs
axiosを使用して仮データを表示していたのをDBのデータを表示するよう修正しました。
レビューお願いします！
> cardにDBのデータを反映させました。

- src/module/page/page.controller.ts
- src/module/request/request.client.ts
- src/module/request/request.controller.ts
- src/module/request/request.type.ts
> getByIdのclient作成

- src/module/request/request.service.ts
> requestのrelations忘れてました、ごめんね

- src/module/item/itemSerializer.ts
- src/module/request/request.controller.ts
- src/module/request/request.serializer.ts
- src/module/request/request.service.ts
getByidで返すデータにitemが含まれるよう修正しました。
動作確認済みです、レビューお願いしますー。
> 依頼情報のデータにitemを含めるように対応

- src/utils/localStrage.ts
localStrageを操作する時に毎回調べるのめんどくさいのでメソッドとしてまとめておきます
> localStrageを操作するためのメソッドを定義

- src/module/page/page.controller.ts
- src/module/page/page.type.ts
- src/module/request/request.client.ts
- src/module/request/request.controller.ts
- src/module/request/request.serializer.ts
- src/module/request/request.type.ts
- src/view/detail.ejs
- src/view/home.ejs
page.controller.ts
page.type.ts
request.client.ts
request.serializer.ts
detail.ejs
home.ejs
の編集
> 依頼詳細画面への遷移と依頼詳細の表示

- src/view/detail.ejs
detail.ejsの編集
(欲しいものの項目についてはまだできていないのでハードコーディングです。)
> 依頼詳細画面のスタイル調整

- frontend/src/app/home/page.tsx
> ホーム画面をNext.jsで書き直す

- frontend/src/app/signup/page.tsx
- frontend/src/features/signup/index.tsx
- #45 にnameを追加しただけです
DBへのデータ追加とローカルストレージにTokenが含まれているかの動作確認済みです
> サインアップ機能作成

- backend/src/index.ts
- backend/src/middleware/setCurrentUser.ts
- backend/src/module/user/user.controller.ts
- backend/src/module/user/user.type.ts
- backend/src/types/express/index.d.ts
setCurrentUserでユーザー情報を返していたのをidのみを返すように修正
getByIdを↑で取得したIDでユーザー情報を返すように修正しました。
> getUserの修正

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/authGuard.tsx
- frontend/src/app/layout.tsx
- frontend/src/component/TopNav.tsx
- frontend/src/features/login/index.tsx
- frontend/src/lib/jotai/userState.ts
認証機能の作成、/requestと/profileの時のみ動きます
> User global state

- backend/src/module/request/request.type.ts
- frontend/src/features/request/index.tsx
userIDを渡していた部分を削除し、Tokenをheaderに含める形でPOSTするようにしました。
> リクエスト作成のフロントとバックを繋げました

- frontend/src/component/BottomNav.tsx
> ButtomNuv　変更

- frontend/src/app/(nav)/profile/page.tsx
Reverts naoyuki2/r6-devteam-firsthalf#53
> Revert "Revert "10/18""

- frontend/src/app/(nav)/home/page.tsx
- frontend/src/component/RequestCard.tsx
home/page.tsxの編集
既存のCard部分をコンポーネントの呼び出しという形に変更
RequestCard.tsxの作成
既存のCard部分をほぼそのまま流用
> Cardコンポーネントを作成

- backend/src/index.ts
- backend/src/migration/1729557426899-room-Column-update.ts
- backend/src/module/room/room.controller.ts
- backend/src/module/room/room.entity.ts
- backend/src/module/room/room.service.ts
- backend/src/module/room/room.type.ts
- backend/src/module/room_user/room_user.service.ts
> room-createAPI作成

- backend/src/module/request/request.controller.ts
- backend/src/module/request/request.service.ts
- backend/src/module/request/request.type.ts
/requestでidによるフィルタとソートができるようになりました。
クエリパラメータでidが渡された場合はそのidが付与されているrequestを返し、渡されなければ全てのrequestを返します。
> /requestのソート、フィルタ完成

- frontend/src/lib/axios/index.ts
> API_URLを設定

- frontend/src/lib/axios/index.ts
> localhostの記述を削除

- frontend/src/features/requestDetail/index.tsx
<h1>操作手順</h1>
ログインしてリクエストを作成後トークンを消す
> ログインしていない場合ログインしようボタンを出す

- backend/src/index.ts
- backend/src/module/room/room.controller.ts
- backend/src/module/room/room.type.ts
- backend/src/utils/soket.type.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/chat/page.tsx
- frontend/src/features/chat/index.tsx
- frontend/src/features/requestDetail/index.tsx
- frontend/src/lib/axios/index.ts
- messageをdbへ登録
- 過去のチャットを表示
- 初期メッセージ、請求書作成
- エラーハンドリング
> チャット機能(途中)

- backend/src/index.ts
- backend/src/migration/1730251522942-message-entity.ts
- backend/src/module/message/message.controller.ts
- backend/src/module/message/message.entity.ts
- backend/src/module/message/message.serializer.ts
- backend/src/module/message/message.service.ts
- backend/src/module/message/message.type.ts
- backend/src/module/user/user.type.ts
- frontend/src/app/authGuard.tsx
- frontend/src/app/user/[id]/page.tsx
- frontend/src/features/chat/index.tsx
- frontend/src/features/signup/index.tsx
- body,roomIdを受け取り、id(message),bodyを返します
- ログイン必須機能
- 動作確認済み
> messageAPI

- backend/src/index.ts
> fix:authorizationChecker内でエラーを返すように修正

- frontend/src/features/requestDetail/index.tsx
- frontend/src/lib/axios/index.ts
> 自分の依頼のチャットするボタンを非表示にする

- frontend/src/app/(nav)/room/page.tsx
- frontend/src/component/TopNav.tsx
- frontend/src/features/room/index.tsx
> Feature/fetch room list　作成

- backend/src/module/message/message.controller.ts
- backend/src/module/message/message.serializer.ts
- backend/src/module/message/message.service.ts
- backend/src/module/message/message.type.ts
- frontend/src/app/chat/[id]/page.tsx
- frontend/src/component/ChatMessage.tsx
- frontend/src/features/chat/hooks.ts
- frontend/src/features/chat/index.tsx
- frontend/src/types/index.ts
> 過去のメッセージ表示できるよ

- backend/src/module/draft_request/draft_request.controller.ts
- backend/src/module/draft_request/draft_request.service.ts
- backend/src/module/draft_request/draft_request.type.ts
---
---
[/draft_requests/proposal{id}]の更新提案APIを作成しました。
idで受け取ったdraft_requestテーブルの情報を元に、req.bodyの内容で更新。
上書きするのではなく、新規でデータを追加します。
> 完成：Feature/draft propose api

- backend/src/module/draft_request/draft_request.controller.ts
- backend/src/module/draft_request/draft_request.serializer.ts
- backend/src/module/draft_request/draft_request.service.ts
- backend/src/module/draft_request/draft_request.type.ts
以下のデータを返します
```Json
{
"draft_request": {
"id": 18,
"title": "東京の限定グッズがほしい",
"location_prefecture": "東京都",
"location_details": "東京ドーム",
"delivery_prefecture": "北海道",
"delivery_details": "札幌",
"description": "東京で開かれるライブの限定グッズ",
"status": "pending",
"completed_at": null,
"created_at": "2024-11-17T15:28:49.470Z",
"updated_at": "2024-11-17T15:28:49.470Z",
"draft_item": [
{
"id": 29,
"name": "東京○○日ライブ限定Tシャツ",
"quantity": 5,
"price": 5000
}
],
"action": true,
"roomId": "9bb92741-c38f-4716-991c-6519a56f9951"
}
}
```
> 完成：Feature/draft approve api

- backend/src/module/draft_requests/draft_request.type.ts
> 下書き依頼取得APIwip

- backend/src/module/draft_request/draft_request.controller.ts
- backend/src/module/draft_request/draft_request.service.ts
- backend/src/module/draft_request/draft_request.type.ts
roomIdを受け取って、最新のdraft_requestを1件返します
> 下書き依頼を取得するAPIの実装

- backend/src/module/draft_request/draft_request.service.ts
- backend/src/module/request/request.controller.ts
- backend/src/module/request/request.service.ts
- backend/src/module/request/request.type.ts
- backend/src/module/room/room.service.ts
roomIdからdraftRequest,requestをもってきて上書きします。
また、上書き処理の終了後draftRequestテーブルからroomIdが含まれている全データを削除します。
> 【締結】依頼を締結するAPIの実装

- backend/src/module/room/room.controller.ts
- backend/src/module/room/room.serializer.ts
> room情報のシリアライザ―を変更

- frontend/src/features/chat/index.tsx
- frontend/src/features/room/index.tsx
- frontend/src/types/index.ts
> errorの修正、フロントの型定義

- backend/src/migration/1732109086046-isAgreed.ts
- backend/src/module/room/room.controller.ts
- backend/src/module/room/room.serializer.ts
- backend/src/module/room_user/room_user.entity.ts
- backend/src/module/room_user/room_user.serializer.ts
- frontend/src/features/room/index.tsx
- frontend/src/types/index.ts
room_userテーブルにisAgreed(同意したか)のカラムを追加しました
またそれにともなってフロント、バックを一部修正しています。
> エンティティの修正、それに伴うフロントの修正

- frontend/package-lock.json
- frontend/package.json
- frontend/src/component/RequestCard.tsx
date-fnsのインストール
RequestCard.tsxの編集
> homeの日付を相対的に表示

- backend/src/index.ts
- backend/src/module/request/request.controller.ts
- backend/src/module/request/request.type.ts
- backend/src/module/room_user/room_user.controller.ts
- backend/src/module/room_user/room_user.service.ts
- backend/src/module/room_user/room_user.type.ts
> isAgreed追加によるAPIの編集、追加

- frontend/src/features/login/index.tsx
- frontend/src/features/request/editrequset/hooks.ts
- frontend/src/features/signup/index.tsx
> /homeへの動線 追加

- backend/src/module/draft_request/draft_request.controller.ts
- backend/src/module/draft_request/draft_request.service.ts
- backend/src/module/draft_request/draft_request.type.ts
- backend/src/module/room/room.controller.ts
- backend/src/module/room/room.serializer.ts
- frontend/src/features/chat/ChatTopNav.tsx
- frontend/src/features/chat/EditModal.tsx
- frontend/src/features/chat/UserStatus.tsx
- frontend/src/features/chat/index.tsx
- frontend/src/features/request/editrequset/index.tsx
- frontend/src/features/request/index.tsx
- frontend/src/lib/axios/index.ts
- frontend/src/types/index.ts
#122 を現在の環境でも動くように調整しました。
運び手がわの拒否、承認の機能を実装してます
> 依頼編集モーダルの実装

- frontend/src/app/layout.tsx
- frontend/src/component/AppUserIcon.tsx
- frontend/src/component/Appbadge.tsx
- frontend/src/component/RequestCard.tsx
- frontend/src/component/Thumbnail.tsx
- frontend/src/features/home/index.tsx
> 依頼のカードのUI修正

- frontend/src/features/chat/ChatMessage.tsx
チャット画面をメッセージが追加されるたびに自動スクロールするようにした。
-動きが微妙に感じたから確認してほしい
> とりあえずuseRef実装してみた

- frontend/src/component/AppArrowRight.tsx
- frontend/src/component/AppCheck.tsx
- frontend/src/features/chat/TodoList.tsx
- frontend/src/features/chat/index.tsx
- frontend/src/types/index.ts
> やることリストの作成

- backend/src/index.ts
- frontend/src/utils/socket.ts
> デプロイ用にurlを追加

- frontend/src/app/(nav)/notifications/page.tsx
- frontend/src/component/BottomNav.tsx
- frontend/src/features/notifications/index.tsx
- frontend/src/types/index.ts
> 通知フロントエンド　作成

- backend/src/index.ts
- backend/src/migration/1733450595041-CreateReview.ts
- backend/src/module/review/review.controller.ts
- backend/src/module/review/review.entity.ts
- backend/src/module/review/review.serializer.ts
- backend/src/module/review/review.service.ts
- backend/src/module/review/review.type.ts
- backend/src/module/user/user.entity.ts
> review用のapiを作成しました

- frontend/src/features/chat/EditModal.tsx
- frontend/src/features/chat/FeedbackForm.tsx
- frontend/src/features/chat/UserStatus.tsx
- frontend/src/features/chat/index.tsx
> レビュー機能の仮実装

- .gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/index.ts
- backend/src/lib/imageUpload.ts
- backend/src/module/user/user.controller.ts
- backend/src/module/user/user.service.ts
- backend/src/module/user/user.type.ts
> 画像をアップロードする機能とuserIconの更新API

- .gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/lib/cloudStorage.ts
- backend/src/lib/croudUprode.ts
- backend/src/lib/imageUpload.ts
- backend/src/module/user/user.controller.ts
> Feature/iage uprode.ts croud uprode

- frontend/src/features/request/index.tsx
> itemのバグを修正

- backend/src/module/review/review.type.ts
- frontend/src/app/request/[id]/page.tsx
- frontend/src/app/review/[id]/page.tsx
- frontend/src/app/user/[id]/page.tsx
- frontend/src/component/AppLink.tsx
- frontend/src/component/RequestCard.tsx
- frontend/src/component/ReviewItem.tsx
- frontend/src/features/chat/FeedbackForm.tsx
- frontend/src/features/home/index.tsx
- frontend/src/features/profile/index.tsx
- frontend/src/features/review/hooks.ts
- frontend/src/features/review/index.tsx
- frontend/src/types/index.ts
**レビューしてもらいたいこと**
-バッジにカスタムcssのinfoを適用させたい
-TopNavにユーザーネームどうやって渡そう？
-Vercelのエラー
ぐらいかな？ほかにあればお願いします！
---
**ここの範囲をdivからaに変更してます**
> 評価一覧画面作成（レビュー対応済み）
